In [19]:
import numpy as np

hw = np.array([
    [0.1, 0.2, 0.4],
    [0.4, 0.6, 0.6],
    [0.5, 0.9, 0.1],
    [0.8, 0.2, 0.8]])
ow = np.array([
    [0.1, 0.6],
    [0.2, 0.1],
    [0.7, 0.9]])

f = np.array([[1.0, 2.0, 3.0, 4.0], [-1.0, -2.0, -3.0, -4.0], [11.0, 12.0, 13.0, 14.0]])

#tf.matmul(features, weights[0])

np.dot(f, hw)
#f.dot(hw)

array([[  5.6,   4.9,   5.1],
       [ -5.6,  -4.9,  -5.1],
       [ 23.6,  23.9,  24.1]])

In [24]:
np.dot(f[0], hw)

array([ 5.6,  4.9,  5.1])

In [25]:
hw0 = np.array([
    [0.1],
    [0.4],
    [0.5],
    [0.8]])
np.dot(f[0], hw0)

array([ 5.6])